file:
  upload-path: C:\Users\BC\Desktop\文件上传

spring:
  web:
    resources:
      static-locations: classpath:/static/,file:${file.upload-path}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB  # 单个⽂件上传⼤⼩
      max-request-size: 100MB  # ⼀次请求上传⽂件⼤⼩

minio:
  endPoint: http://127.0.0.1:9000
  accessKey: admin
  secretKey: admin123